### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by caecos** [bsp2/VeeSeeVSTRack#9]
I notices that the folder dist has disapeared and the the vst2_bin does not have the requested dll...you are surely overload with works...

**Comment by bsp2** [comment]
Git repositories are not really meant for storing (large) binaries and the repository size had grown out of proportion (almost 7 gigabytes!).
That's why I deleted the binary releases and moved the files to Github's large file storage (LFS).

Well, what they didn't tell you was that the LFS is limited to 1GByte bandwidth, which was exceeded very quickly.
Now the files are in a dedicated [releases](https://github.com/bsp2/releases/tree/master/vsvr) repo, which I will clean up (remove older releases) every now and then.

Besides, you should always download the full .7z (see [Downloads](https://github.com/bsp2/VeeSeeVSTRack#downloads) section) to make sure that all assets (e.g. module .svg files) are up-to-date / in sync with the binaries.

**Comment by caecos** [comment]
Thanks for the fast reply...What I liked of the old dist folder was that there was 32 and 64 bits and I run Reaper 32 bits and Cubase 64 bits...so...I'll tried not to burn your bandwidth to fast… ;D
